services:
  santander.api1:
    image: ${DOCKER_REGISTRY-}santandercodechallengeapi
    build:
      context: .
      dockerfile: Santander.CodeChallenge.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      redis:
        condition: service_healthy

  santander.api2:
    image: ${DOCKER_REGISTRY-}santandercodechallengeapi
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      santander.api1:
        condition: service_started
      redis:
        condition: service_healthy

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 3s
      retries: 10

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      santander.api1:
        condition: service_started
      santander.api2:
        condition: service_started
    ports:
      - "8088:80"
    volumes:
      - ./nginx/santander.conf:/etc/nginx/nginx.conf:ro
